### ISSUE TITLE
Action not marked as failed if an error occurs

### ISSUE THREAD

**Issue by Nef10** [BetaHuhn/repo-file-sync-action#93]
**🐞 Describe the bug**

The actions run is marked as success even though an error occurred.

**📚 To Reproduce**

Use an invalid token, or a token which does not have correct access.

**💡 Expected behavior**

The workflow run should be marked as failed.

**🖼️ Screenshots**

See
https://github.com/Nef10/swift-package-common/actions/runs/1178374879
https://github.com/Nef10/swift-package-common/actions/runs/1178388705

**⚙️ Environment**

`BetaHuhn/repo-file-sync-action@v1`

**Comment by BetaHuhn** [comment]
Hey, thanks for reporting this!

It appears to be a bug in how the action catches errors:

https://github.com/BetaHuhn/repo-file-sync-action/blob/beedb2cf5002ee06c89256d3654c39cbf4a6a0d0/src/index.js#L170-L173

It should set the action to failed with `core.setFailed(err.message)` as it does here:

https://github.com/BetaHuhn/repo-file-sync-action/blob/beedb2cf5002ee06c89256d3654c39cbf4a6a0d0/src/index.js#L185-L190

**Comment by BetaHuhn** [comment]
Actually, just remembered why it is handled that way:

When syncing files to multiple repositories the action goes through each one individually. If an error occurs while handling one, it just logs it and goes to the next repository instead of failing the whole action. The action only fails when an error occurs during startup/getting the inputs and when parsing the sync config.

I guess when it only syncs to one repository it makes sense to fail the action when an error occurs, else the current approach is better IMO as it will at least try to sync to the other repositories if one fails.

What do you think?

**Comment by BetaHuhn** [comment]
Yeah, makes sense. It should fail the action but still try to sync as many repositories as possible.
